Homework7
den10004/MortalKombat pull request #7
Opened 2021-06-15 17:52 UTC by den10004

сделано

2021-06-15 20:57 UTC, ZarMarathon requested changes
перечитай тз, у тебя в main должен остаться только обработчик на форме и вызоа функций для создания игроков

2021-06-15 20:57 UTC, ZarMarathon commented on main.js
> +        alert('ошибка')
alert блокирует интерфейс, лучше что-то другое
ну и break тоже нужен в дефолтном

2021-06-15 20:57 UTC, ZarMarathon commented on main.js
> +    }
почему лог defence то не вызываешь?

2021-06-16 06:21 UTC, den10004 commented on main.js
> +        alert('ошибка')
исправлено

2021-06-16 06:27 UTC, den10004 commented on main.js
> +    }
исправлено

2021-06-20 07:24 UTC, merged